workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: Virtual Lobby Technology
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.vlobby.app
      vars:
        APP_STORE_APPLE_ID: 6736442782
        XCODE_WORKSPACE: "apps/vlobby-app/ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        
    scripts:
      - name: Install pnpm
        script: |
          if ! command -v pnpm &> /dev/null; then
            npm install -g pnpm
          else
            echo "pnpm is already installed"
          fi
      - name: Install dependencies
        script: |
          pnpm install
      - name: Cocoapods installation
        script: |
          cd apps/vlobby-app/ios/App && pod install
      - name: Update dependencies and copy web assets to native project
        script: |
          cd apps/vlobby-app
          pnpm run build
          npx cap sync
      - name: Set up code signing settings on Xcode project
        script: |
          cd apps/vlobby-app/ios/App
          xcode-project use-profiles
      - name: Set build number
        script: | 
          #!/bin/sh
          cd $CM_BUILD_DIR/apps/vlobby-app/ios/App
          NEW_BUILD_NUMBER="1.0.4"
          echo "Setting build number to: $NEW_BUILD_NUMBER"
          agvtool new-version -all $NEW_BUILD_NUMBER
          
          # Verify the new build number
          CURRENT_BUILD_NUMBER=$(agvtool what-version -terse)
          echo "Current build number after update: $CURRENT_BUILD_NUMBER"
          
          if [ "$CURRENT_BUILD_NUMBER" != "$NEW_BUILD_NUMBER" ]; then
            echo "Error: Build number was not updated correctly"
            exit 1
          fi
      - name: Build ipa for distribution
        script: |
          cd $CM_BUILD_DIR/apps/vlobby-app/ios/App
          xcode-project build-ipa \
            --workspace "App.xcworkspace" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - apps/vlobby-app/ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - zach.kingsford@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - vlobby-beta-testers
        submit_to_app_store: false